version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@1
jobs:
  generate-config:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Generate Pipeline generated_config.yml file
          command: |
            sudo apt-get update
            sudo apt-get install -y gettext-base
            .circleci/scripts/generate-pipeline-config
      - continuation/continue:
          parameters: "{}"
          configuration_path: .circleci/configs/generated_config.yml
workflows:
  setup-workflow:
    jobs:
      - generate-config:
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
