#!/bin/env bash

set -euo pipefail

PYTHON_VERSION=$(cat .python-version) #Python Version to install
POETRY_VERSION="$(cat .tool-versions | grep poetry | cut -d ' ' -f 2)"
VERSION=${CIRCLE_TAG:-${CIRCLE_SHA1:0:7}}

# Use \$ to escape the variables to be replaced when the pipeline is running
# eg: ${VERSION} -> \${VERSION}

mkdir -p .circleci/configs/
CI_TEMPLATE_PYTHON_VERSION=${PYTHON_VERSION} \
    CI_TEMPLATE_POETRY_VERSION=${POETRY_VERSION} \
    CI_TEMPLATE_VERSION=${VERSION} \
    envsubst '$CI_TEMPLATE_PYTHON_VERSION $CI_TEMPLATE_POETRY_VERSION $CI_TEMPLATE_VERSION' < .circleci/scripts/template.yml > .circleci/configs/generated_config.yml
