#!/bin/env bash

set -euo pipefail

RUST_VERSION="$(grep rust .tool-versions | cut -d ' ' -f 2)"
VERSION=${CIRCLE_TAG:-${CIRCLE_SHA1:0:7}}

mkdir -p .circleci/configs/

CI_TEMPLATE_RUST_VERSION=${RUST_VERSION} \
    CI_TEMPLATE_VERSION=${VERSION} \
    envsubst '$CI_TEMPLATE_RUST_VERSION $CI_TEMPLATE_VERSION' < .circleci/scripts/template.yml > .circleci/configs/generated_config.yml
